export const OTLP_ENDPOINT = process.env.OTLP_LOGS_ENDPOINT!;
export const OTLP_AUTH_HEADER_NAME = process.env.OTLP_AUTH_HEADER_NAME!;
export const OTLP_AUTH_HEADER_VALUE = process.env.OTLP_AUTH_HEADER_VALUE!;
export const OTLP_LOGGER_ENABLED = process.env.OTLP_LOGGER_ENABLED!;
export const OTLP_LOGGER_LEVEL = process.env.OTLP_LOGGER_LEVEL!;
export const PG_URL = process.env.PG_URL!;
export const NATS_URL = process.env.NATS_URL!;
export const NATS_TOKEN = process.env.NATS_TOKEN!;
// true = run the API-serving worker inside this admin process (testing);
// false = admin is control-plane only, a separate worker node serves user APIs.
export const ENABLE_BUILTIN_WORKER = process.env.ENABLE_BUILTIN_WORKER!;
